substitutions:
  device_name: "e-vlxesp32"
  friendly_name: "E-VLXESP32"
  project_name: "PG_LAB_Electronics.E-VLXESP32"
  project_version: "1.0"
  ap_pwd: "password"

esphome:

  name: "${device_name}"
  name_add_mac_suffix: true
  friendly_name: "${friendly_name}"
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ap:
    ssid: "${friendly_name} Hotspot"
    password: "${ap_pwd}"

logger:

time:
  - platform: homeassistant

captive_portal:

web_server:

i2c:
  sda: GPIO3
  scl: GPIO2
  scan: true
  id: bus_a

sensor:
  - platform: hdc1080
    temperature:
      name: "Temperature"
      filters:
       - offset: -2.6
    humidity:
      name: "Humidity"
    address: 0x40
    update_interval: 60s

switch:
  - platform: gpio
    name: "Down"
    id: velux_down
    icon: "mdi:window-shutter"
    pin: 
      number: GPIO1
    on_turn_on:
     - delay: 200ms
     - switch.turn_off: velux_down
    interlock: [velux_up, velux_stop]
    internal: true

  - platform: gpio
    name: "Stop"
    id: velux_stop
    icon: "mdi:window-shutter"
    pin: 
      number: GPIO7
    on_turn_on:
     - delay: 200ms
     - switch.turn_off: velux_stop
    interlock: [velux_down, velux_up]
    internal: true

  - platform: gpio
    name: "Up"
    id: velux_up
    icon: "mdi:window-shutter"
    pin: 
     number: GPIO5
    on_turn_on:
     - delay: 200ms
     - switch.turn_off: velux_up
    interlock: [velux_down, velux_stop]
    internal: true

  - platform: gpio
    pin: GPIO10
    name: "Led Green"
    internal: false

binary_sensor:
  - platform: gpio
    id: sense_up
    pin:
      number: GPIO04
      mode:
        input: true
        pullup: true
    filters:
      - lambda: !lambda return !(x || id(velux_up).state);
    on_press:
      then:
        - cover.open: shutter
  - platform: gpio
    id: sense_stop
    pin:
      number: GPIO06
      mode:
        input: true
        pullup: true
    filters:
      - lambda: !lambda return !(x || id(velux_stop).state);
    on_press:
      then:
        - cover.stop: shutter
    on_double_click:
      min_length: 30ms
      max_length: 250ms
      then:
        - homeassistant.event:
            event: esphome.velux_double_click
  - platform: gpio
    id: sense_down
    pin:
      number: GPIO00
      mode:
        input: true
        pullup: true
    filters:
      - lambda: !lambda return !(x || id(velux_down).state);
    on_press:
      then:
        - cover.close: shutter

cover:
  - platform: time_based
    id: shutter
    name: "Shutter"
    has_built_in_endstop: true
    manual_control: true
    assumed_state: true

    open_action:
      - switch.turn_on: velux_up
    open_duration: 30s # measure this

    close_action:
      - switch.turn_on: velux_down
    close_duration: 30s # measure this

    stop_action:
      - switch.turn_on: velux_stop

